### ISSUE TITLE
PrintNodePrinter deserialization issue

### ISSUE THREAD

**Issue by petarvu** [christianz/printnode-net#1]
Firstly, great wrapper for PrintNode!

When `JsonConvert.DeserializeObject<List<PrintNodePrinter>>(response)` is called in both ListAsync() and GetAsync(long id).

And response contains following
`{
...
"papers": {
        "Letter": [2159, 2794],
        "w288h360": [null, null]
}
...
}`

It will fail with deserialization exception, can't cast null to value-type. I'm currently using a quick workaround by replacing **[null, null]** with **[0, 0]** in the response before deserializing.

_I have not cloned the repo and tested, but I think it should work if PrintNodePrinterCapabilities.Papers is set to type with nullable **int?[]** `Dictionary<string, int?[]>`._

**Comment by christianz** [comment]
Hi Petar, thanks for your comment!

Could you give me the printer type and model you are using to get these results? This, to me, looks like a bug in the results that PrintNode sends back to us.

If it's not a bug or I don't hear back from their tech support, I'll add your suggestion to the code and build a new version.

**Comment by petarvu** [comment]
Got 2 printers TSC TDP 244 ZPL and HP LaserJet Professional P1102, both returned [null, null] for some of the paper values. Also I'm using OS X (El Capitan).

**Comment by christianz** [comment]
Hi Petar,

this is the response I got from PrintNode:

> Hi Christian,
> 
> You're right it would be better if this was { "<identifier>": [288, 360] } but this is a driver limitation and not a PrintNode thing.
> 
> Integer dimensions are returned by the operating systems printer drivers. In this case the calls don't > return values or make this information available in any other way so PrintNode can't return anything > meaningful. It just so happens this information is encoded in the "media name" but this can't be relied upon. It would be possible to "name" a media "w288h360" and assign dimensions to it which had no relation to either 288 or 360.
> 
> The fact that these can be null is documented in the API docs. https://www.printnode.com/docs/api/curl/#printer-capabilities See "papers" description.
> 
> The values you can use for the "paper" property when building a "options" object are on of the keys in the "capabilties", "papers" object. The dimensions array is there for informational / descriptive purposes and not for actually selecting which media to print to.

This looks like an OS X thing.

For now I will fix the code by including your suggestion. In the future it might be valuable to make a new class to contain the width and height properties, and give it a special state where it doesn't have any information, to handle these situations.

Can you try to update your nuget package to the latest version (1.0.12) and test again with your printers?

**Comment by petarvu** [comment]
Works like a charm!
