### ISSUE TITLE
Add the ability to customize BaseUri 

### ISSUE THREAD

**Issue by Aleksandr-Kuznetsov** [christianz/printnode-net#13]
At the moment, BaseUri is hardcoded inside the PrintNodeApiHelper. It makes it impossible to use the library for specific API's. Is it possible to move BaseUri to the settings?

**Comment by christianz** [comment]
Hi Aleksandr. What would this be used for? Can you give me an example of an alternate base address you might use?

**Comment by Aleksandr-Kuznetsov** [comment]
Sure! For example, we have the following BaseUri: "companyname-api.printnode.com"

**Comment by christianz** [comment]
I've pushed the changes to https://github.com/christianz/printnode-net/tree/feature/customizable-baseaddress

Can you pull the code from that branch and check that it works for your use case? I updated the README with instructions for setting the base address.

**Comment by Aleksandr-Kuznetsov** [comment]
It looks amazing! Absolutely works for my case, thanks!

**Comment by Aleksandr-Kuznetsov** [comment]
Will be these changes available in nuget?

**Comment by christianz** [comment]
Yep - now! 😄 
https://www.nuget.org/packages/PrintNode.Net/1.1.4
