### ISSUE TITLE
Sets & printjob deletion not handled yet

### ISSUE THREAD

**Issue by RedNeath** [christianz/printnode-net#15]
Hey! Thanks for this neat tool for PrintNode, it really helps 👍

Although, looking at the code, it seems that there is no possibility to specify [sets](https://www.printnode.com/fr/docs/api/curl#parameters) yet.  
For the route [GET`/printers/PRINTER SET/printjobs`](https://www.printnode.com/fr/docs/api/curl#printjob-viewing) for instance, I found in the source code that there was a method in the class [PrintNodePrinter](https://github.com/christianz/printnode-net/blob/master/PrintNodePrintJob.cs#LC128) : ListForPrinterAsync that uses it, but the only parameter we can pass to it is a long, instead of an enumerable.
I also couldn't find a method for making a call to the [DELETE`/printjobs/PRINT JOB SET`](https://www.printnode.com/fr/docs/api/curl#printjobs-removing) route.

Are these things you're planning to work on, or should I just go straight and fork to add them in? Or perhaps there is a reason you didn't do these?

Thanks for your time.
Have a nice day!

**Comment by christianz** [comment]
Hi! I'm not sure why set support was never added. Most likely it was not a requirement when I first started building the library several years ago, or it hadn't been added to the PrintNode API yet.

If you would like to add support for this through a pull request, please do so!

**Comment by christianz** [comment]
Thanks for your contribution! The Nuget has been updated and is available at https://www.nuget.org/packages/PrintNode.Net/1.1.5
